name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest  # Puede usar ubuntu, windows o mac

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Descarga tu código del repositorio

    - name: Set up JDK 11
      uses: actions/setup-java@v1  # Configura Java (si es un proyecto Java)
      with:
        java-version: '11'

    - name: Cache SonarCloud dependencies
      uses: actions/cache@v2  # Caché para las dependencias de SonarCloud
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.java') }}
        restore-keys: |
          ${{ runner.os }}-sonar-

    - name: Run SonarCloud analysis
      us
